<?php

$router
    ->get(
        'source',
        '/Source\.html',
        'Generic'
    )
    ->get(
        'literature',
        '/Literature\.html',
        'Generic'
    )
    ->get(
        'learn',
        '/Literature/Learn/(?<chapter>\w+)\.html',
        'Literature\Learn'
    )
    ->get(
        'hack',
        '/Literature/Hack/(?<chapter>[\w ]+)\.html',
        'Literature\Hack'
    )
    ->get(
        'minitutorial',
        '/Literature/Mini-tutorial\.html',
        'Literature\Minitutorial'
    )
    ->get(
        'research',
        '/Literature/Research/(?<article>[\w\d]+)\.pdf',
        'Literature\Research'
    )
    ->get(
        'videos',
        '/Video\.html',
        'Video\Video'
    )
    ->get(
        'awecode',
        '/Awecode/(?<id>[\w\-_]+)\.html',
        'Video\Awecode'
    )
    ->get(
        'events',
        '/Event\.html',
        'Generic'
    )
    ->get(
        'event',
        '/Event/(?<event>\w+)\.html',
        'Generic'
    )
    ->get(
        'community',
        '/Community\.html',
        'Generic'
    )
    ->get(
        'about',
        '/About\.html',
        'Generic'
    )
    ->get(
        'foundation',
        '/Foundation.html',
        'Generic'
    )
    ->get(
        'foundation+',
        '/Foundation/(?<page>\w+)\.html',
        'Generic'
    )
    ->head_get(
        'home',
        '/',
        'Generic'
    );
